'use strict';

import * as Constructions from "./CONSTRUCTIONS.js";

class CodeFactory {

    /**
     * Generate code
     */
    static generate(editor) {
        let variableNames = ["blueprint", "blueprint_of_doom", "blueprint42", "your_blueprint", "blueprint_X"];
        let variable = variableNames[Math.floor(Math.random() * variableNames.length)];

        let content = "//Generated by BlueScreeps 1.0.0\r\nlet " + variable + " = (room_, x, y) => _.each([";
        let breakAfter = 5;

        for (let i in editor.instances) {
            let construct = editor.instances[i];
            if (construct instanceof Constructions.Construction) {
                if (i % breakAfter === 0 && parseInt(i) !== 0 && parseInt(i) !== editor.instances.length-1)
                    content += "\r\n";
                let {x, y} = editor.getGridPos(construct.position.x, construct.position.y);
                content += "[" + construct.type + ", " + x / editor.GRID_BOX_SIZE + ", " + y / editor.GRID_BOX_SIZE + "], ";
            }
        }
        if (editor.instances.length > 0)
            content = content.slice(0, content.length - 2);
        content += "], (s) => {room_.createConstructionSite(x+s[1], y+s[2], s[0]);});\r\n\r\nmodule.exports = {" + variable + "};";

        return content;
    }
}

export {CodeFactory};